/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/Login copy.vue')['default']
    CreateUserModal: typeof import('./src/components/CreateUserModal.vue')['default']
    FormCreateUser: typeof import('./src/components/FormCreateUser.vue')['default']
    FormUpdateUser: typeof import('./src/components/FormUpdateUser.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    ListUser: typeof import('./src/components/ListUser.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    PageLogin: typeof import('./src/components/PageLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    UpdateUserModal: typeof import('./src/components/UpdateUserModal.vue')['default']
  }
}
